==== stdout ====

==== stderr ====
[1m[32m    Finished[0m release [optimized] target(s) in 0.35s
[1m[32m     Running[0m `target\release\examples\update_gltf_scene.exe`
[2m2024-03-22T07:31:55.613347Z[0m [32m INFO[0m [2mbevy_winit::system[0m[2m:[0m Creating new window "App" (Entity { index: 0, generation: 1 })
[2m2024-03-22T07:31:55.665440Z[0m [32m INFO[0m [2mbevy_render::renderer[0m[2m:[0m AdapterInfo { name: "Microsoft Basic Render Driver", vendor: 5140, device: 140, device_type: Cpu, driver: "", driver_info: "", backend: Dx12 }
[2m2024-03-22T07:31:55.719136Z[0m [33m WARN[0m [2mbevy_audio::audio_output[0m[2m:[0m No audio device found.
[2m2024-03-22T07:31:55.944315Z[0m [32m INFO[0m [2mbevy_diagnostic::system_information_diagnostics_plugin::internal[0m[2m:[0m SystemInfo { os: "Windows Server 2022 Datacenter", kernel: "20348", cpu: "AMD EPYC 7763 64-Core Processor", core_count: "2", memory: "16.0 GiB" }
[2m2024-03-22T07:32:04.864902Z[0m [31mERROR[0m [2mwgpu_core::device::global[0m[2m:[0m Device::create_render_pipeline error: Internal error in ShaderStages(VERTEX | FRAGMENT) shader: 0x887A0005    
[2m2024-03-22T07:32:04.864951Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Shader translation error for stage ShaderStages(VERTEX | FRAGMENT): 0x887A0005    
[2m2024-03-22T07:32:04.864960Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Please report it to https://github.com/gfx-rs/wgpu    
[2m2024-03-22T07:32:04.864978Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Async Compute Task Pool (0)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_prepass_pipeline`
    Internal error in ShaderStages(VERTEX | FRAGMENT) shader: 0x887A0005


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2m2024-03-22T07:32:04.890441Z[0m [31mERROR[0m [2mwgpu_core::device::global[0m[2m:[0m Device::create_render_pipeline error: Internal error in ShaderStages(VERTEX | FRAGMENT) shader: 0x887A0005    
[2m2024-03-22T07:32:04.890469Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Shader translation error for stage ShaderStages(VERTEX | FRAGMENT): 0x887A0005    
[2m2024-03-22T07:32:04.890475Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Please report it to https://github.com/gfx-rs/wgpu    
[2m2024-03-22T07:32:04.890485Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Async Compute Task Pool (0)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_prepass_pipeline`
    Internal error in ShaderStages(VERTEX | FRAGMENT) shader: 0x887A0005


[2m2024-03-22T07:32:04.893100Z[0m [31mERROR[0m [2mwgpu_hal::auxil::dxgi::result[0m[2m:[0m Root signature creation failed: 0x887A0005    
[2m2024-03-22T07:32:04.893156Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Async Compute Task Pool (0)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_pipeline_layout
    Parent device is lost


[2m2024-03-22T07:32:04.896132Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (1)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer_with
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_pbr::render::light::prepare_lights`!
[2m2024-03-22T07:32:04.896515Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (1)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_render::globals::prepare_globals_buffer`!
[2m2024-03-22T07:32:04.896655Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer_with
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_pbr::render::fog::prepare_fog`!
[2m2024-03-22T07:32:04.896773Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (1)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer_with
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_pbr::light_probe::upload_light_probes`!
[2m2024-03-22T07:32:04.896904Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_pbr::render::light::prepare_clusters`!
[2m2024-03-22T07:32:04.896970Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (1)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer_with
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_render::view::prepare_view_uniforms`!
[2m2024-03-22T07:32:04.897100Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_pbr::render::skin::prepare_skins`!
[2m2024-03-22T07:32:04.897361Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (1)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_render::batching::write_batched_instance_buffer<bevy_sprite::mesh2d::mesh::Mesh2dPipeline>`!
[2m2024-03-22T07:32:04.897471Z[0m [31mERROR[0m [2mwgpu::backend::wgpu_core[0m[2m:[0m Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer
    Creation of a resource failed for a reason other than running out of memory.


Encountered a panic in system `bevy_render::batching::write_batched_instance_buffer<bevy_pbr::render::mesh::MeshPipeline>`!
thread 'Async Compute Task Pool (0)' panicked at crates\bevy_render\src\render_resource\pipeline_cache.rs:700:60:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'Async Compute Task Pool (0)' panicked at crates\bevy_render\src\render_resource\pipeline_cache.rs:700:Encountered a panic in system `60bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system:
`!
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at D:\a\bevy-example-runner\bevy-example-runner\crates\bevy_render\src\render_phase\draw.rs:294:54:
called `Result::unwrap()` on an `Err` value: QueryDoesNotMatch(Entity { index: 2, generation: 1 })
thread '<unnamed>' panicked at D:\a\bevy-example-runner\bevy-example-runner\crates\bevy_render\src\diagnostic\mod.rs:157:9:
PassSpanScope::end was never called
stack backtrace:
   0:     0x7ff6ed410112 - <unknown>
   1:     0x7ff6ed42ae1d - <unknown>
   2:     0x7ff6ed40c511 - <unknown>
   3:     0x7ff6ed40ff3a - <unknown>
   4:     0x7ff6ed4120e9 - <unknown>
   5:     0x7ff6ed411da5 - <unknown>
   6:     0x7ff6ed412604 - <unknown>
   7:     0x7ff6ed41249b - <unknown>
   8:     0x7ff6ed4107b9 - <unknown>
   9:     0x7ff6ed4121a6 - <unknown>
  10:     0x7ff6ed54d677 - <unknown>
  11:     0x7ff6ec3e679a - <unknown>
  12:     0x7ffaaf551030 - <unknown>
  13:     0x7ffaaf554ede - is_exception_typeof
  14:     0x7ffaaf55f400 - _C_specific_handler
  15:     0x7ffaaf55414c - is_exception_typeof
  16:     0x7ffaaf55fd41 - _CxxFrameHandler3
  17:     0x7ffabde8443f - _chkstk
  18:     0x7ffabde0f10c - RtlUnwindEx
  19:     0x7ffaaf55f8ce - _C_specific_handler
  20:     0x7ffaaf552e05 - is_exception_typeof
  21:     0x7ffaaf553224 - is_exception_typeof
  22:     0x7ffaaf554248 - is_exception_typeof
  23:     0x7ffaaf55fd41 - _CxxFrameHandler3
  24:     0x7ffabde843bf - _chkstk
  25:     0x7ffabde1186e - RtlVirtualUnwind2
  26:     0x7ffabde2f6d1 - RtlRaiseException
  27:     0x7ffabb40f19c - RaiseException
  28:     0x7ffaaf5566c0 - CxxThrowException
  29:     0x7ff6ed41a5ce - <unknown>
  30:     0x7ff6ed412959 - <unknown>
  31:     0x7ff6ed41266d - <unknown>
  32:     0x7ff6ed4124d9 - <unknown>
  33:     0x7ff6ed4107b9 - <unknown>
  34:     0x7ff6ed4121a6 - <unknown>
  35:     0x7ff6ed54d677 - <unknown>
  36:     0x7ff6ed54dbb3 - <unknown>
  37:     0x7ff6ec246f03 - <unknown>
  38:     0x7ff6ec3f01bc - <unknown>
  39:     0x7ff6ec3e65d5 - <unknown>
  40:     0x7ff6ec364d8e - <unknown>
  41:     0x7ff6ec72b343 - <unknown>
  42:     0x7ff6ec72b46e - <unknown>
  43:     0x7ff6ec729cb3 - <unknown>
  44:     0x7ff6ec88a998 - <unknown>
  45:     0x7ff6ec7dd5b4 - <unknown>
  46:     0x7ff6ed35970d - <unknown>
  47:     0x7ff6ed3924f9 - <unknown>
  48:     0x7ff6ed3908a9 - <unknown>
  49:     0x7ff6ed398f96 - <unknown>
  50:     0x7ff6ed38b041 - <unknown>
  51:     0x7ff6ed38d872 - <unknown>
  52:     0x7ff6ed393336 - <unknown>
  53:     0x7ff6ed382e29 - <unknown>
  54:     0x7ff6ed35e8d2 - <unknown>
  55:     0x7ff6ed34750c - <unknown>
  56:     0x7ff6ed33ddbb - <unknown>
  57:     0x7ff6ec7a3fda - <unknown>
  58:     0x7ff6ec94f1bb - <unknown>
  59:     0x7ff6ed417b2c - <unknown>
  60:     0x7ffabc324cb0 - BaseThreadInitThunk
  61:     0x7ffabde5e8ab - RtlUserThreadStart
[1m[31merror[0m[1m:[0m process didn't exit successfully: `target\release\examples\update_gltf_scene.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
